setTimeout(() => {
    console.log('RrRRRR')
    console.log('RrRRRR')
    console.log('RrRRRR')
    console.log('RrRRRR')
    console.log('RrRRRR')
    console.log('RrRRRR')
    console.log('RrRRRR')
    console.log('RrRRRR')
    console.log('RrRRRR')
    console.log('RrRRRR')
    console.log('RrRRRR')
    console.log('RrRRRR')
    console.log('RrRRRR')
}, (1000));